module Ballerina.DSL.Codegen.Python.Tests.Header

open NUnit.Framework
open Ballerina.Core.StringBuilder
open Ballerina.DSL.Codegen.Python.LanguageConstructs.Model

[<Test>]
let ``Test should create sorted imports`` () =
  let imports =
    [ 
      Import "from x import y"
      Import "from dataclasses import dataclass"
      Import "from collections.abc import Sequence" ]
    |> Set.ofList

  let actual = Ballerina.DSL.Codegen.Python.LanguageConstructs.Header.Generate imports |> StringBuilder.ToString

  let expected =
    """# Code generated by ballerina, DO NOT EDIT.

from __future__ import annotations
from collections.abc import Sequence
from dataclasses import dataclass
from x import y

"""

  Assert.That(actual, Is.EqualTo expected)

// TODO: Implement behavior for grouped imports
// [<Test>]
// let ``Test should create grouped imports`` () =
//   let imports =
//     [ 
//       Import "from collections.abc import Sequence"
//       Import "from collections.abc import Mapping" ]
//     |> Set.ofList

//   let actual = Ballerina.DSL.Codegen.Python.LanguageConstructs.Header.Generate imports |> StringBuilder.ToString

//   let expected =
//     """# Code generated by ballerina, DO NOT EDIT.

// from __future__ import annotations
// from collections.abc import Mapping, Sequence

// """

//   Assert.That(actual, Is.EqualTo expected)
