namespace Ballerina.DSL.Codegen.Python.LanguageConstructs

[<RequireQualifiedAccess>]
module Header =
  open Ballerina.Core.StringBuilder
  open System
  open Ballerina.DSL.Codegen.Python.LanguageConstructs.Model

  let Generate (imports: Set<Import>) =
    StringBuilder.One
      $$"""# Code generated by ballerina, DO NOT EDIT.

from __future__ import annotations
{{ String.Join("\n",
     imports
     |> Set.map (fun i -> $"from {i.Source} import {i.Target}")
     |> List.ofSeq
     |> List.sort
   )
}}

"""
