namespace Codegen.Python

[<RequireQualifiedAccess>]
module Header =
  open Ballerina.StdLib.StringBuilder
  open System
  open Codegen.Python.Model

  let Generate (imports: Set<Import>) =
    let groupImportsBySource =
      List.ofSeq
      >> List.groupBy (fun i -> i.Source)
      >> List.map (fun (source, importsOfSource) ->
        { Source = source
          Target =
            importsOfSource
            |> List.map (fun i -> i.Target)
            |> List.sort
            |> String.concat ", " })
      >> Set.ofList

    StringBuilder.One
      $$"""# Code generated by ballerina, DO NOT EDIT.

from __future__ import annotations
{{String.Join(
    "\n",
    imports
    |> groupImportsBySource
    |> Set.map (fun i -> sprintf "from %s import %s" i.Source i.Target)
    |> List.ofSeq
    |> List.sort
  )}}

"""
