FROM node:22.15.0@sha256:a1f1274dadd49738bcd4cf552af43354bb781a7e9e3bc984cfeedc55aba2ddd8 AS build-web

ARG UID=
ARG GID=

COPY ./docker/startup-web.sh /bin/startup
RUN chmod +x /bin/startup

RUN groupmod -g $GID node && \
    usermod -u $UID -g $GID node && \
    mkdir -p /app && chown -R $UID:$GID /app
    
RUN chown $UID:$GID /bin/startup

USER node

WORKDIR /app

ENTRYPOINT ["sh", "/bin/startup"]