namespace Codegen.Golang


module Header =
  open Ballerina.StdLib
  open Ballerina.StdLib.StringBuilder
  open Syntax

  type Header =
    { Imports: Set<GoImport>
      PackageName: string }

  let private formatImport (GoImport import) : StringBuilder =
    StringBuilder.One(sprintf "\"%s\"" import)

  type Header with
    static member Generate
      ({ Imports = imports
         PackageName = packageName }: Header)
      : StringBuilder =

      StringBuilder.Many
        [ StringBuilder.One "// Code generated by ballerina, DO NOT EDIT."
          StringBuilder.One $"package {packageName}"
          StringBuilder.One "import ("
          StringBuilder.Many(imports |> Seq.map formatImport) |> StringBuilder.Map indent
          StringBuilder.One ")" ]
      |> StringBuilder.Map appendNewline
