export enum DATE_FORMAT {
    DATE = "DATE",
    DATE_DAY_MONTH = "DATE_DAY_MONTH",
    DATE_TIME = "DATE_TIME",
    TIME_SHORT = "TIME_SHORT",
    TIME = "TIME",
    DATE_DAY_OF_WEEK = "DATE_DAY_OF_WEEK",
    DATE_DAY_OF_MONTH = "DATE_DAY_OF_MONTH",
    DATE_WEEK_OF_YEAR = "DATE_WEEK_OF_YEAR",
    DATE_MONTH_NUMERIC = "DATE_MONTH_NUMERIC",
    DATE_MONTH_SHORT = "DATE_MONTH_SHORT",
    DATE_MONTH_LONG_YEAR = "DATE_MONTH_LONG_YEAR",
    DATE_YEAR = "DATE_YEAR",
    DATE_DAY_MONTH_SHORT_YEAR = "DATE_DAY_MONTH_SHORT_YEAR",
    
}

export const THROTTLE_TIME = 1000;