name: CI
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v6.0.2
      - run: yarn
      - run: yarn prettier:check
      - run: yarn compile-ballerina-core

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: "10.0.201"
      - run: dotnet tool restore
      - run: dotnet build backend
      # - run: dotnet fantomas --check backend

  ballerina-samples-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: "10.0.201"
      - run: dotnet tool restore
      - run: dotnet run --project backend/apps/ballerina-samples-integration-test/ballerina-samples-integration-test.fsproj -- --verbose
